name: 'APT'
description: 'Use apt to install packages and architectures'
author: 'ryan kurte'
inputs:
  architectures:
    description: 'architectures to pass to dpkg --add-architecture'
  packages:
    description: 'apt packages to install`

runs:
  using: 'node12'
  main: 'dist/index.js'

