name: 'apt multiarch helper action'
description: 'Use apt to setup a foreign architecture (multiarch) and install packages on ubuntu'
author: 'ryan kurte'
inputs:
  arch:
    description: 'Foreign architecture to configure'
    required: true
  distro:
    description: 'Distribution name'
    required: true
    default: 'focal'
  packages:
    description: 'List of packages to install'
    required: true

runs:
  using: 'composite'
  steps:
    - name: "Patch azure archives for [amd64, i386] use only"
      shell: bash
      run: |
        sudo sed -i'' -E 's/^(deb|deb-src) http:\/\/(azure.archive|security).ubuntu.com/\1 [arch=amd64,i386] http:\/\/\2.ubuntu.com/' /etc/apt/sources.list

    - name: "Add foreign architecture (${{ inputs.arch }}"
      shell: bash
      run: sudo dpkg --add-architecture ${{ inputs.arch }}

    - name: "Add ports.ubuntu.com sources to /etc/apt/sources.list.d/${{ inputs.arch }}.list"
      shell: bash
      run: |
        echo "deb [arch=${{ inputs.arch }}] http://ports.ubuntu.com/ubuntu-ports/ ${{ inputs.distro }} main restricted universe" | sudo tee /etc/apt/sources.list.d/${{ inputs.arch }}.list
        echo "deb [arch=${{ inputs.arch }}] http://ports.ubuntu.com/ubuntu-ports/ ${{ inputs.distro }}-updates main restricted universe" | sudo tee -a /etc/apt/sources.list.d/${{ inputs.arch }}.list
        echo "deb [arch=${{ inputs.arch }}] http://ports.ubuntu.com/ubuntu-ports/ ${{ inputs.distro }}-backports main restricted universe "| sudo tee -a /etc/apt/sources.list.d/${{ inputs.arch }}.list
        echo "deb [arch=${{ inputs.arch }}] http://ports.ubuntu.com/ubuntu-ports/ ${{ inputs.distro }}-security main restricted universe" | sudo tee -a /etc/apt/sources.list.d/${{ inputs.arch }}.list

    - name: "Update apt"
      shell: bash
      run: sudo apt update

    - name: "Install packages"
      shell: bash
      run: sudo apt-get install -y ${{ inputs.packages }}

branding:
  icon: 'arrow-down-circle'  
  color: 'blue'
